# Cloudflare Pages Configuration
name = "ai-generate-station"
compatibility_date = "2024-01-15"
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production.vars]
NODE_ENV = "production"
DATABASE_URL = "d1-remote"

[env.preview.vars]
NODE_ENV = "production"
DATABASE_URL = "d1-remote"

# D1 Database bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "ai-generate-station-db"
database_id = "" # This will be filled by the deployment script

[[env.preview.d1_databases]]
binding = "DB"
database_name = "ai-generate-station-db-preview"
database_id = "" # For preview environment

# KV namespace bindings (if needed for caching)
# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = ""

# R2 bucket bindings (if needed for file storage)
# [[env.production.r2_buckets]]
# binding = "STORAGE"
# bucket_name = "ai-generate-station-storage"

# Analytics and monitoring
[observability]
enabled = true

# Miniflare configuration for local development
[miniflare]
kv_persist = true
d1_persist = true
cache_persist = true